# Phishing URL Detection Using Machine Learning

## Notebook 01 — Dataset Description and Initial Understanding

---

## 1. Introduction

Phishing is a major cybersecurity threat in which attackers attempt to deceive users by creating fraudulent websites or URLs that appear to be associated with legitimate organizations, services, or online platforms.

The main objective of a phishing attack is often to trick users into providing sensitive information such as usernames, passwords, banking credentials, payment information, or other confidential data.

Because phishing websites can closely resemble legitimate websites, manually identifying whether a URL is trustworthy can be difficult for ordinary users. Therefore, automated phishing detection techniques can play an important role in improving online security.

Machine Learning provides a way to automatically learn patterns from previously observed data. By analyzing characteristics of URLs and webpages, a Machine Learning model can learn differences between phishing and legitimate websites and use those patterns to classify previously unseen URLs.

This project focuses on developing a Machine Learning-based system for **Phishing URL Detection**.

---

## 2. Project Title

**Phishing URL Detection Using Machine Learning**

The project aims to develop a classification system that analyzes URL and webpage-related characteristics and predicts whether a URL belongs to the phishing or legitimate class.

---

## 3. Problem Statement

Phishing URLs can be difficult to distinguish from legitimate URLs because attackers may use techniques such as:

- Long or unusual URLs
- Suspicious domain structures
- Excessive special characters
- IP addresses instead of domain names
- Multiple subdomains
- URL redirections
- Fake webpage titles
- Suspicious external references
- Hidden webpage elements
- Other characteristics designed to imitate legitimate websites

Traditional rule-based approaches may not always generalize effectively to new phishing patterns.

Therefore, this project investigates the use of Machine Learning algorithms to learn patterns from URL and webpage characteristics and classify URLs into two categories:

**Phishing** or **Legitimate**.

---

## 4. Aim of the Project

The main aim of this project is to design and evaluate a Machine Learning classification system for detecting phishing URLs.

The system will use URL and webpage-related features as input and predict the corresponding class of the URL.

### General Workflow

The project follows the following Machine Learning workflow:

1. Dataset Collection and Understanding
2. Data Preprocessing
3. Exploratory Data Analysis
4. Feature Engineering
5. Feature Selection
6. Model Building and Training
7. Hyperparameter Tuning
8. Model Evaluation
9. Model Comparison
10. Final Prediction and Demonstration

---

## 5. Objectives of the Project

The major objectives of this project are:

### Objective 1 — Dataset Understanding

To understand the structure, characteristics, variables, and target classes present in the phishing URL dataset.

### Objective 2 — Data Preprocessing

To prepare the raw dataset for Machine Learning by handling issues such as missing values, duplicate records, categorical variables, and feature scaling where required.

### Objective 3 — Exploratory Data Analysis

To analyze the statistical properties and relationships among different features and identify patterns associated with phishing and legitimate URLs.

### Objective 4 — Feature Engineering

To investigate whether meaningful new features can be derived from the available URL and webpage characteristics.

### Objective 5 — Feature Selection

To identify useful predictive features and reduce unnecessary or redundant information where appropriate.

### Objective 6 — Model Development

To implement suitable Machine Learning classification algorithms for phishing URL detection.

### Objective 7 — Hyperparameter Optimization

To tune important model parameters using an appropriate validation and cross-validation strategy.

### Objective 8 — Model Evaluation

To evaluate the developed models using appropriate classification metrics such as:

- Accuracy
- Precision
- Recall
- F1-score
- ROC-AUC
- Confusion Matrix
- Classification Report

### Objective 9 — Model Comparison

To compare the implemented Machine Learning models using consistent evaluation metrics and identify the model that provides the strongest performance on the evaluation data.

### Objective 10 — Final Demonstration

To demonstrate the final selected model using sample or previously unseen input and obtain a predicted phishing or legitimate classification.

---

## 6. Machine Learning Problem Definition

This project is formulated as a **Supervised Binary Classification** problem.

### Supervised Learning

The dataset contains input features along with a known target label.

The Machine Learning algorithm learns the relationship between the input features and their corresponding target classes during training.

### Binary Classification

The target variable contains two classes.

The model will learn to distinguish between:

- **Phishing URL**
- **Legitimate URL**

### Input

The input consists of URL and webpage-related characteristics such as URL structure, domain characteristics, webpage properties, references, security indicators, and other relevant features available in the dataset.

### Output

The expected output is the predicted class of the URL:

**Phishing** or **Legitimate**.

---

## 7. Project Input and Output

The general prediction process can be represented as:

    URL / Webpage Characteristics
                |
                v
        Data Preprocessing
                |
                v
        Feature Representation
                |
                v
        Machine Learning Model
                |
                v
             Prediction
                |
          +-----+-----+
          |           |
          v           v
      Phishing    Legitimate

The Machine Learning model will learn from historical labelled examples and apply the learned patterns to unseen data.

---

## 8. Dataset Used

The project uses the **PhiUSIIL Phishing URL (Website) Dataset**.

The dataset contains URL and webpage-related characteristics that can be used for Machine Learning-based phishing detection.

A detailed description of the dataset, including:

- Dataset source
- Number of records
- Number of columns
- Feature names
- Data types
- Target variable
- Target class distribution
- Missing values
- Duplicate records
- Unique values

will be performed in the following sections of this notebook using the actual uploaded CSV file.

---

## 9. Target Variable

The target variable used in this project is:

`label`

The target represents the class assigned to each URL.

The two target classes are:

- **0 — Phishing URL**
- **1 — Legitimate URL**

The exact class distribution will be calculated directly from the dataset during the dataset analysis stage.

---

## 10. Importance of Phishing URL Detection

Automated phishing detection can be useful in cybersecurity applications because it can assist in identifying suspicious URLs before users interact with potentially fraudulent websites.

A Machine Learning-based system can analyze multiple characteristics simultaneously rather than relying on a single rule or URL property.

Such a system can potentially be used as a supporting component in:

- Web browsers
- Email security systems
- Security monitoring systems
- URL scanning applications
- Cybersecurity tools
- Web filtering systems

The purpose of this academic project is to investigate the effectiveness of Machine Learning techniques for this classification task.

---

## 11. Scope of the Project

The scope of this project includes:

- Understanding the provided phishing URL dataset.
- Preparing the dataset for Machine Learning.
- Performing exploratory analysis.
- Investigating relevant features.
- Training multiple classification algorithms.
- Tuning selected models.
- Evaluating model performance.
- Comparing the implemented models.
- Demonstrating prediction using the final selected model.

The project focuses on Machine Learning-based classification using the available dataset and does not attempt to replace complete enterprise-level cybersecurity systems.

---

## 12. Evaluation Approach

Since this is a binary classification problem, model performance will not be evaluated using accuracy alone.

The project will consider multiple evaluation metrics:

### Accuracy

Measures the proportion of correctly classified observations among all observations.

### Precision

Measures the proportion of predicted positive cases that are actually positive.

### Recall

Measures the proportion of actual positive cases correctly identified by the model.

### F1-score

Provides a combined measure based on precision and recall.

### ROC-AUC

Measures the model's ability to distinguish between the two classes across different classification thresholds.

### Confusion Matrix

Provides a detailed view of correct and incorrect predictions for each class.

The exact evaluation results will be calculated after the models are trained.

---

## 13. Notebook 01 Objectives

This notebook specifically focuses on **Dataset Description and Initial Understanding**.

The following activities will be performed in this notebook:

1. Import the required Python libraries.
2. Load the PhiUSIIL dataset.
3. Verify the dataset dimensions.
4. Inspect the dataset structure.
5. Display the feature names.
6. Examine the data types.
7. Separate predictive features, metadata, and target information.
8. Analyze the target variable.
9. Calculate the target class distribution.
10. Check for missing values.
11. Check for duplicate records.
12. Analyze URL-level duplication.
13. Examine unique values and feature cardinality.
14. Identify constant features.
15. Generate descriptive statistics.
16. Summarize the initial data quality.
17. Document important observations for subsequent preprocessing.

---

## 14. Machine Learning Project Pipeline

The complete project will follow this pipeline:

    Raw Dataset
         |
         v
    Dataset Understanding
         |
         v
    Data Preprocessing
         |
         v
    Exploratory Data Analysis
         |
         v
    Feature Engineering
         |
         v
    Feature Selection
         |
         v
    Model Building
         |
         v
    Hyperparameter Tuning
         |
         v
    Model Evaluation
         |
         v
    Model Comparison
         |
         v
    Final Prediction

Each stage will be documented using both Python implementation and corresponding outputs or visualizations.

---

## 15. Expected Outcome

At the end of the complete project, a Machine Learning-based phishing URL classification system will be developed and evaluated.

The final system will accept the required URL-related feature information and produce a classification indicating whether the input belongs to the phishing or legitimate class.

The project will also provide a comparison of different Machine Learning algorithms and document their performance using appropriate evaluation metrics.

---

## 16. Notebook Documentation Principle

This project follows the principle that a Jupyter Notebook should contain both:

**Implementation + Results + Interpretation**

Therefore, the notebooks will not contain code alone.

Important sections will include:

- Explanation in Markdown cells
- Python implementation in Code cells
- Actual execution output
- Tables and visualizations where appropriate
- Observations and interpretations

All numerical results reported in the notebooks will be generated from the actual dataset used in this project.

In [2]:
# Importing required libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("All required libraries imported successfully.")

All required libraries imported successfully.

# 1. Dataset Description

## 1.1 Dataset Source

The dataset used in this project is the **PhiUSIIL Phishing URL (Website) Dataset**.

The dataset is designed for research and Machine Learning applications related to the identification of phishing and legitimate websites.

### Dataset Information

- **Dataset Name:** PhiUSIIL Phishing URL (Website) Dataset
- **Dataset Type:** Supervised Classification Dataset
- **Problem Type:** Binary Classification
- **Target Variable:** `label`
- **Number of Records:** 235,795
- **Number of Columns:** 56
- **Predictive Features:** 54
- **Metadata Column:** `FILENAME`
- **Classes:** Phishing and Legitimate

### Official Dataset Source

The dataset is available through the UCI Machine Learning Repository.

The official source will be referenced in the project report to maintain reproducibility and provide proper dataset attribution.

---

## 1.2 Dataset Purpose

The purpose of this dataset is to provide labelled examples of websites that can be used to develop and evaluate Machine Learning models for phishing detection.

Each record represents a website or URL together with a collection of characteristics describing different aspects of the URL and webpage.

These characteristics can include information related to:

- URL structure
- Domain properties
- Webpage characteristics
- Security-related indicators
- External references
- HTML or webpage behaviour
- Other measurable website properties

The target variable indicates whether the corresponding website belongs to the phishing or legitimate class.

---

## 1.3 Dataset Structure

The dataset can be conceptually divided into three parts:

### 1. Predictive Features

These are the variables that may contain useful information for predicting the target class.

The dataset contains **54 predictive features** according to the official dataset documentation.

### 2. Metadata

The column `FILENAME` is metadata associated with the dataset and is not intended to be used as a predictive feature.

Therefore, it will be excluded from the Machine Learning feature matrix during later preprocessing.

### 3. Target Variable

The `label` column represents the target variable.

It contains the class assigned to each website.

The target mapping is:

| Label | Meaning |
|------:|---------|
| 0 | Phishing |
| 1 | Legitimate |

---

## 1.4 Machine Learning Representation

For Machine Learning, the dataset can be represented as:

**Input Features (X)**

The selected URL and webpage characteristics.

**Target (y)**

The `label` column representing the website class.

Conceptually:

    X = URL and webpage characteristics
    |
    v
    Machine Learning Model
    |
    v
    y = Phishing / Legitimate

The objective is to learn a relationship between the input features and the target class using the training data.

---

## 1.5 Why Dataset Understanding Is Important

Before applying any Machine Learning algorithm, it is important to understand the dataset.

Incorrect assumptions about:

- feature types,
- missing values,
- duplicate records,
- target classes,
- metadata columns,
- categorical variables,
- numerical variables,

can lead to incorrect preprocessing and unreliable model results.

Therefore, this notebook first performs a systematic examination of the dataset before beginning the actual preprocessing stage.

The following cells will inspect the actual CSV file and verify the dataset information programmatically.

---

## 1.6 Dataset Analysis Plan

The dataset will be analyzed using the following sequence:

1. Load the CSV file.
2. Display the first few records.
3. Determine the number of rows and columns.
4. Display all column names.
5. Identify data types.
6. Identify the target variable.
7. Analyze target class distribution.
8. Check missing values.
9. Check duplicate rows.
10. Examine duplicate URLs where applicable.
11. Analyze feature cardinality.
12. Identify constant features.
13. Generate descriptive statistics.
14. Summarize the initial dataset quality.

All numerical values reported in the following sections will be obtained directly from the uploaded dataset rather than being manually entered.

---

## 1.7 Reproducibility

The analysis is performed using Python and commonly used data-analysis libraries.

The dataset is loaded directly from the project directory:

    ML_Project/
    ├── dataset/
    │   └── PhiUSIIL_Phishing_URL_Dataset.csv
    │
    └── notebooks/
        └── 01_Dataset_Description.ipynb

Since this notebook is located inside the `notebooks` directory, the dataset can be accessed using the relative path:

    ../dataset/PhiUSIIL_Phishing_URL_Dataset.csv

Using a relative path makes the project easier to reproduce when the complete project folder is moved to another computer.

---

## 1.8 Important Data-Leakage Consideration

The target variable `label` must not be used as an input feature.

Similarly, metadata such as `FILENAME` will not be treated as a predictive feature.

During later stages of the project, the dataset will be divided into training and testing data before fitting preprocessing transformations and Machine Learning models.

This is important to prevent information from the test dataset from influencing the training process.

The final evaluation dataset will remain isolated until model evaluation.

---

## 1.9 Initial Dataset Description Summary

At this stage, the project has established the expected structure of the dataset:

- The task is a binary classification problem.
- The target variable is `label`.
- The dataset contains phishing and legitimate website examples.
- The dataset contains URL and webpage-related characteristics.
- `FILENAME` is metadata and will not be used as a predictive feature.
- The actual dataset structure will be verified using Python in the next cells.
- All subsequent preprocessing and modelling decisions will be based on the observed dataset characteristics.

In [3]:
# Loading the PhiUSIIL Phishing URL Dataset

dataset_path = r"C:\Users\Hitesh\OneDrive\Desktop\ML_Project_Work\dataset\PhiUSIIL_Phishing_URL_Dataset.csv"

df = pd.read_csv(dataset_path)

print("Dataset loaded successfully!")
print("Dataset shape:", df.shape)

Dataset loaded successfully!
Dataset shape: (235795, 56)

# 1.10 Initial Dataset Inspection

After loading the dataset, the next step is to inspect the actual records.

This initial inspection helps us understand how the data is organized before performing preprocessing.

The following analysis will examine:

- The first few records of the dataset
- The last few records
- The total number of rows and columns
- The structure of the dataset
- The names of all available columns

Inspecting the records is important because it allows us to verify that the dataset has been loaded correctly and that the expected URL, webpage, metadata, and target information are present.

The results obtained from the following code will be used as the basis for subsequent dataset analysis and preprocessing decisions.

In [4]:
# Displaying the first five records of the dataset

print("First 5 records of the dataset:")
display(df.head())

First 5 records of the dataset:

,FILENAME,URL,URLLength,Domain,DomainLength,IsDomainIP,TLD,URLSimilarityIndex,CharContinuationRate,TLDLegitimateProb,...,Pay,Crypto,HasCopyrightInfo,NoOfImage,NoOfCSS,NoOfJS,NoOfSelfRef,NoOfEmptyRef,NoOfExternalRef,label
0,521848.txt,https://www.southbankmosaics.com,31,www.southbankmosaics.com,24,0,com,100.0,1.000000,0.522907,...,0,0,1,34,20,28,119,0,124,1
1,31372.txt,https://www.uni-mainz.de,23,www.uni-mainz.de,16,0,de,100.0,0.666667,0.032650,...,0,0,1,50,9,8,39,0,217,1
2,597387.txt,https://www.voicefmradio.co.uk,29,www.voicefmradio.co.uk,22,0,uk,100.0,0.866667,0.028555,...,0,0,1,10,2,7,42,2,5,1
3,554095.txt,https://www.sfnmjournal.com,26,www.sfnmjournal.com,19,0,com,100.0,1.000000,0.522907,...,1,1,1,3,27,15,22,1,31,1
4,151578.txt,https://www.rewildingargentina.org,33,www.rewildingargentina.org,26,0,org,100.0,1.000000,0.079963,...,1,0,1,244,15,34,72,1,85,1

# 1.11 Dataset Dimensions

The dimensions of a dataset indicate the number of observations and variables available for analysis.

In this project:

- **Rows** represent individual website or URL records.
- **Columns** represent the different characteristics, metadata fields, and target information associated with each record.

Determining the dataset dimensions is important because it confirms the size of the dataset and helps us understand the scale of the Machine Learning problem.

The dimensions will be obtained directly from the loaded DataFrame using Python.

In [5]:
# Displaying the number of records and columns

rows, columns = df.shape

print("Number of records (rows):", rows)
print("Number of columns:", columns)
print("Dataset dimensions:", df.shape)

Number of records (rows): 235795
Number of columns: 56
Dataset dimensions: (235795, 56)

# 1.12 Feature and Column Names

A dataset contains multiple columns representing different variables.

Examining the complete list of column names is important because it helps us:

- Identify the available predictive features.
- Identify the target variable.
- Identify metadata columns.
- Understand the different types of URL and webpage characteristics.
- Prepare the dataset correctly for later preprocessing and feature selection.

The PhiUSIIL dataset contains **56 columns** in total.

According to the dataset documentation, the `label` column is the target variable, while `FILENAME` is metadata and will not be used as a predictive feature.

The complete list of columns will be displayed directly from the loaded DataFrame in the next code cell.

In [6]:
# Displaying all column names

print("Total number of columns:", len(df.columns))
print("\nColumn names:\n")

for i, column in enumerate(df.columns, start=1):
    print(f"{i}. {column}")

Total number of columns: 56

Column names:

1. FILENAME
2. URL
3. URLLength
4. Domain
5. DomainLength
6. IsDomainIP
7. TLD
8. URLSimilarityIndex
9. CharContinuationRate
10. TLDLegitimateProb
11. URLCharProb
12. TLDLength
13. NoOfSubDomain
14. HasObfuscation
15. NoOfObfuscatedChar
16. ObfuscationRatio
17. NoOfLettersInURL
18. LetterRatioInURL
19. NoOfDegitsInURL
20. DegitRatioInURL
21. NoOfEqualsInURL
22. NoOfQMarkInURL
23. NoOfAmpersandInURL
24. NoOfOtherSpecialCharsInURL
25. SpacialCharRatioInURL
26. IsHTTPS
27. LineOfCode
28. LargestLineLength
29. HasTitle
30. Title
31. DomainTitleMatchScore
32. URLTitleMatchScore
33. HasFavicon
34. Robots
35. IsResponsive
36. NoOfURLRedirect
37. NoOfSelfRedirect
38. HasDescription
39. NoOfPopup
40. NoOfiFrame
41. HasExternalFormSubmit
42. HasSocialNet
43. HasSubmitButton
44. HasHiddenFields
45. HasPasswordField
46. Bank
47. Pay
48. Crypto
49. HasCopyrightInfo
50. NoOfImage
51. NoOfCSS
52. NoOfJS
53. NoOfSelfRef
54. NoOfEmptyRef
55. NoOfExternalRef
56. label

# 1.13 Understanding the Dataset Columns

The dataset contains 56 columns representing different types of information related to websites and URLs.

For Machine Learning, it is important to distinguish between:

### 1. Metadata

`FILENAME` is a metadata column.

It identifies information associated with the source file or record and is not intended to represent a predictive characteristic of the website.

Therefore, it will not be included in the final predictive feature matrix.

### 2. URL and Website Features

The dataset contains numerous features describing properties of URLs and websites.

Examples visible in the dataset include:

- `URL`
- `URLLength`
- `Domain`
- `DomainLength`
- `IsDomainIP`
- `TLD`
- `URLSimilarityIndex`
- `CharContinuationRate`
- `TLDLegitimateProb`
- `URLCharProb`
- `NoOfSubDomain`
- `HasObfuscation`
- `NoOfObfuscatedChar`
- `ObfuscationRatio`
- `NoOfLettersInURL`
- `LetterRatioInURL`
- `NoOfDigitsInURL`
- `DigitRatioInURL`
- `NoOfEqualsInURL`

Additional URL and webpage-related features are present in the remaining columns.

### 3. Target Variable

The column:

`label`

is the target variable.

It represents the class that the Machine Learning model will learn to predict.

The target mapping is:

| Label | Class |
|---:|---|
| 0 | Phishing |
| 1 | Legitimate |

### 4. Feature Matrix and Target

For the later Machine Learning stages, the dataset will conceptually be separated into:

**Predictive features (X)**  
→ Website and URL characteristics used by the model.

**Target (y)**  
→ `label`

**Excluded metadata**  
→ `FILENAME`

The exact feature list will be verified programmatically rather than manually entered.

This separation is important for preventing metadata and target information from accidentally becoming model inputs.

In [7]:
# Displaying the complete list of column names without truncation

pd.set_option("display.max_rows", None)

column_table = pd.DataFrame({
    "Column Number": range(1, len(df.columns) + 1),
    "Column Name": df.columns
})

display(column_table)

    Column Number                 Column Name
0               1                    FILENAME
1               2                         URL
2               3                   URLLength
3               4                      Domain
4               5                DomainLength
5               6                  IsDomainIP
6               7                         TLD
7               8          URLSimilarityIndex
8               9        CharContinuationRate
9              10           TLDLegitimateProb
10             11                 URLCharProb
11             12                   TLDLength
12             13               NoOfSubDomain
13             14              HasObfuscation
14             15          NoOfObfuscatedChar
15             16            ObfuscationRatio
16             17            NoOfLettersInURL
17             18            LetterRatioInURL
18             19             NoOfDegitsInURL
19             20             DegitRatioInURL
20             21             NoOfEqualsInURL
21             22              NoOfQMarkInURL
22             23          NoOfAmpersandInURL
23             24  NoOfOtherSpecialCharsInURL
24             25       SpacialCharRatioInURL
25             26                     IsHTTPS
26             27                  LineOfCode
27             28           LargestLineLength
28             29                    HasTitle
29             30                       Title
30             31       DomainTitleMatchScore
31             32          URLTitleMatchScore
32             33                  HasFavicon
33             34                      Robots
34             35                IsResponsive
35             36             NoOfURLRedirect
36             37            NoOfSelfRedirect
37             38              HasDescription
38             39                   NoOfPopup
39             40                  NoOfiFrame
40             41       HasExternalFormSubmit
41             42                HasSocialNet
42             43             HasSubmitButton
43             44             HasHiddenFields
44             45            HasPasswordField
45             46                        Bank
46             47                         Pay
47             48                      Crypto
48             49            HasCopyrightInfo
49             50                   NoOfImage
50             51                     NoOfCSS
51             52                      NoOfJS
52             53                 NoOfSelfRef
53             54                NoOfEmptyRef
54             55             NoOfExternalRef
55             56                       label

# 1.14 Data Types of Dataset Features

Data types describe the kind of values stored in each column.

Understanding data types is important because different types of variables require different preprocessing techniques.

The main categories that will be examined are:

### Numerical Features

Numerical features contain values that can be used directly in mathematical calculations.

Examples include:

- URL length
- Domain length
- Number of subdomains
- Number of digits
- Ratio-based features
- Probability-based features

Numerical features are generally suitable for Machine Learning algorithms after applying the required preprocessing and scaling.

### Categorical or Text Features

Some columns contain text or categorical information.

Examples include:

- `URL`
- `Domain`
- `TLD`
- `Title`

These columns require special consideration because raw text or high-cardinality categorical values should not automatically be treated as ordinary numerical features.

### Metadata

`FILENAME` is treated as metadata and will not be used as a predictive feature.

### Target

`label` is the target variable containing the two classification classes:

- `0` — Phishing
- `1` — Legitimate

The exact data type of every column will be obtained directly from the DataFrame in the next code cell.

# 1.15 Target Variable Analysis

The target variable is the variable that the Machine Learning model is expected to predict.

For this project, the target variable is:

`label`

The target contains two classes, making this a **binary classification problem**.

## Target Class Mapping

According to the dataset documentation:

| Label | Class |
|---:|---|
| 0 | Phishing |
| 1 | Legitimate |

### Phishing — Label 0

A value of `0` represents a phishing website.

These records correspond to websites identified as phishing examples in the dataset.

### Legitimate — Label 1

A value of `1` represents a legitimate website.

These records correspond to websites identified as legitimate examples in the dataset.

## Importance of Target Analysis

Understanding the target distribution is important because an unequal number of observations between classes can affect Machine Learning model training and evaluation.

For example, if one class contains substantially more observations than the other, accuracy alone may not provide a complete picture of model performance.

Therefore, this project will examine:

- Number of observations in each class
- Percentage of each class
- Whether the dataset is balanced or imbalanced
- Distribution of phishing and legitimate records

The actual class counts and percentages will be calculated directly from the dataset in the next code cell.

In [8]:
# Analyzing the target class distribution

target_counts = df["label"].value_counts().sort_index()

target_distribution = pd.DataFrame({
    "Label": target_counts.index,
    "Class": ["Phishing" if label == 0 else "Legitimate" for label in target_counts.index],
    "Count": target_counts.values,
    "Percentage": (target_counts.values / len(df) * 100).round(2)
})

display(target_distribution)

print("Total records:", len(df))

   Label       Class   Count  Percentage
0      0    Phishing  100945       42.81
1      1  Legitimate  134850       57.19

Total records: 235795

# 1.16 Target Class Distribution — Interpretation

The target variable contains two classes: phishing and legitimate websites.

The analysis of the actual dataset produced the following distribution:

| Label | Class | Number of Records | Percentage |
|---:|---|---:|---:|
| 0 | Phishing | 100,945 | 42.81% |
| 1 | Legitimate | 134,850 | 57.19% |
| **Total** | | **235,795** | **100.00%** |

## Observations

### 1. Phishing Class

There are **100,945 phishing records**, representing approximately **42.81%** of the dataset.

### 2. Legitimate Class

There are **134,850 legitimate records**, representing approximately **57.19%** of the dataset.

### 3. Class Balance

The two classes are not exactly equal in size.

However, both classes contain a substantial number of observations. Therefore, the dataset does not consist of a single dominant class.

For model evaluation, multiple metrics such as **precision, recall, F1-score, ROC-AUC, and the confusion matrix** will be considered instead of relying only on accuracy.

### 4. Importance for Model Development

The target distribution should be considered when splitting the dataset into training and testing sets.

A **stratified split** can be used during the Machine Learning stage so that the relative representation of the two target classes is maintained across the training and testing datasets.

## Conclusion

The dataset contains a sufficiently large number of examples from both target classes:

- **42.81% Phishing**
- **57.19% Legitimate**

This target distribution will be considered during subsequent preprocessing, model training, and evaluation.

# 1.17 Data Type Summary

The data type of each column determines how the feature should be handled during data preprocessing.

The dataset contains different types of variables, including numerical and text-based columns.

Understanding the data types is important for selecting appropriate preprocessing techniques such as:

- Numerical feature scaling
- Categorical encoding
- Text feature handling
- Metadata removal
- Target separation

The complete data type distribution will be calculated directly from the DataFrame.

The analysis will identify:

1. Number of integer columns
2. Number of floating-point columns
3. Number of object/text columns
4. Data type of the target variable
5. Data type of the metadata column

No data transformation will be performed at this stage. This step is only for understanding the original dataset structure.

In [10]:
# Calculating the actual data type summary

dtype_counts = df.dtypes.value_counts()

print("Number of columns by data type:")
print(dtype_counts)

print("\nTarget variable data type:")
print("label:", df["label"].dtype)

print("\nMetadata column data type:")
print("FILENAME:", df["FILENAME"].dtype)

Number of columns by data type:
int64      41
float64    10
str         5
Name: count, dtype: int64

Target variable data type:
label: int64

Metadata column data type:
FILENAME: str

# 1.18 Data Type Interpretation

The data type analysis was performed directly on the loaded dataset.

The results are:

| Data Type | Number of Columns |
|---|---:|
| Integer (`int64`) | 41 |
| Floating-point (`float64`) | 10 |
| String/Object (`str`) | 5 |
| **Total** | **56** |

## Target Variable

The target variable `label` has the data type:

`int64`

This is appropriate for a binary classification target because the two classes are represented using numerical labels:

- `0` — Phishing
- `1` — Legitimate

## Metadata Column

The `FILENAME` column has the data type:

`str`

It is treated as metadata and will not be used as a predictive feature in the Machine Learning models.

## Numerical Features

The dataset contains 41 integer columns and 10 floating-point columns.

These numerical variables include measurements such as:

- URL lengths
- Character counts
- Ratios
- Probabilities
- Domain-related measurements
- Reference counts
- Other numerical website characteristics

These features can be examined using statistical analysis and, where appropriate, scaled during preprocessing.

## Text/Object Features

The dataset contains 5 string/object columns.

These columns require additional examination before deciding how they should be handled.

Raw text or high-cardinality values should not automatically be one-hot encoded because this could create a very large number of features and may not provide an appropriate representation for the Machine Learning models.

The exact object/string columns will therefore be identified in the next analysis step.

## Conclusion

The dataset contains a mixture of numerical and text-based information.

Therefore, the preprocessing stage will need to:

1. Separate the target variable.
2. Exclude metadata.
3. Identify numerical features.
4. Identify text/object features.
5. Determine an appropriate treatment for each feature type.
6. Avoid unnecessary or high-cardinality transformations.

In [11]:
# Identifying all text/object columns

object_columns = df.select_dtypes(include=["object"]).columns.tolist()

print("Number of text/object columns:", len(object_columns))
print("\nText/Object columns:")

for i, column in enumerate(object_columns, start=1):
    print(f"{i}. {column}")

Number of text/object columns: 5

Text/Object columns:
1. FILENAME
2. URL
3. Domain
4. TLD
5. Title

C:\Users\Hitesh\AppData\Local\Temp\ipykernel_16192\1887556620.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  object_columns = df.select_dtypes(include=["object"]).columns.tolist()

# 1.19 Text/Object Feature Interpretation

The dataset contains five columns with a text/object data type.

The actual columns identified from the dataset are:

| No. | Column | Role |
|---:|---|---|
| 1 | `FILENAME` | Metadata |
| 2 | `URL` | URL/Text feature |
| 3 | `Domain` | Domain/Text feature |
| 4 | `TLD` | Categorical/Text feature |
| 5 | `Title` | Webpage/Text feature |

## 1. FILENAME

`FILENAME` contains string values and is treated as metadata.

It will be excluded from the predictive feature matrix because it does not represent a direct characteristic of the website that the model needs to learn.

## 2. URL

`URL` contains the complete URL string.

The raw URL contains potentially useful information, but it is a high-cardinality text field. Therefore, it should not automatically be converted into thousands of one-hot encoded categories.

The dataset already provides numerical URL characteristics such as URL length, character counts, digit ratios, and other URL-related measurements.

These engineered numerical characteristics can be used during Machine Learning instead of directly encoding every unique raw URL.

## 3. Domain

`Domain` contains domain names.

Similar to the raw URL, domain names can have very high cardinality. Direct one-hot encoding may therefore create a large and sparse feature space.

The available numerical domain-related features will be examined before deciding how this column should be handled.

## 4. TLD

`TLD` represents the Top-Level Domain information.

This is a categorical/text feature. Its number of unique values and frequency distribution will be examined before selecting an encoding strategy.

## 5. Title

`Title` contains webpage title information.

Webpage titles are text data and may contain a large number of unique values. Therefore, the raw `Title` column will require careful consideration rather than automatic one-hot encoding.

## Preprocessing Decision

At this stage, no text encoding or feature removal is performed.

The columns will first be examined using:

- Number of unique values
- Missing values
- Frequency distributions
- Duplicate values
- Relationship with the target where appropriate

The final preprocessing decision will be documented later based on the observed data characteristics.

In [12]:
# Analyzing unique values in text/object columns

text_columns = ["FILENAME", "URL", "Domain", "TLD", "Title"]

unique_value_table = pd.DataFrame({
    "Column": text_columns,
    "Unique Values": [df[column].nunique(dropna=False) for column in text_columns],
    "Total Records": [len(df)] * len(text_columns)
})

unique_value_table["Unique Percentage"] = (
    unique_value_table["Unique Values"] /
    unique_value_table["Total Records"] * 100
).round(2)

display(unique_value_table)

     Column  Unique Values  Total Records  Unique Percentage
0  FILENAME         235795         235795             100.00
1       URL         235370         235795              99.82
2    Domain         220086         235795              93.34
3       TLD            695         235795               0.29
4     Title         197874         235795              83.92

# 1.20 Cardinality Analysis of Text/Object Columns

Cardinality refers to the number of distinct values present in a feature.

Analyzing cardinality is important when working with categorical or text features because a feature with a very large number of unique values may create an unnecessarily large feature space if it is directly one-hot encoded.

The actual cardinality analysis produced the following results:

| Column | Unique Values | Unique Percentage |
|---|---:|---:|
| `FILENAME` | 235,795 | 100.00% |
| `URL` | 235,370 | 99.82% |
| `Domain` | 220,086 | 93.34% |
| `TLD` | 695 | 0.29% |
| `Title` | 197,874 | 83.92% |

## 1. FILENAME

`FILENAME` contains 235,795 unique values, corresponding to 100% of the records.

Since it behaves as metadata and has no intended predictive role, it will be excluded from the Machine Learning feature set.

## 2. URL

`URL` contains 235,370 unique values, corresponding to 99.82% of the dataset.

This indicates extremely high cardinality.

Direct one-hot encoding of the complete URL would therefore create an unsuitable and very large categorical representation.

The dataset already contains several numerical features that describe URL characteristics. These features can be investigated as predictive inputs instead of directly encoding each complete URL.

## 3. Domain

`Domain` contains 220,086 unique values, corresponding to 93.34% of the records.

This is also a high-cardinality feature.

Direct one-hot encoding of domain names could create a large feature space and may reduce the practicality of the Machine Learning pipeline.

Therefore, the raw `Domain` column requires careful treatment.

## 4. TLD

`TLD` contains 695 unique values, representing approximately 0.29% of the total number of records.

Compared with the other text columns, `TLD` has substantially lower cardinality.

Its distribution and relationship with the target will be examined before selecting an appropriate encoding strategy.

## 5. Title

`Title` contains 197,874 unique values, representing approximately 83.92% of the records.

This indicates high cardinality.

Direct one-hot encoding of the complete webpage title would produce a large and sparse feature representation.

Therefore, the raw `Title` column will not automatically be one-hot encoded.

## Preprocessing Implications

Based on the cardinality analysis:

- `FILENAME` will be excluded as metadata.
- `URL` will not be directly one-hot encoded because of its extremely high cardinality.
- `Domain` will not be directly one-hot encoded because of its high cardinality.
- `Title` will not be directly one-hot encoded because of its high cardinality.
- `TLD` has comparatively lower cardinality and will be examined further before choosing an encoding method.

No feature is removed solely from this analysis. The final treatment will be documented after examining the feature distributions, missing values, and predictive usefulness.

## Conclusion

The cardinality analysis demonstrates that the raw text columns have very different characteristics.

The numerical URL and webpage features provided by the dataset will therefore be important candidates for the Machine Learning feature matrix, while categorical/text columns will require appropriate preprocessing decisions.

# 1.21 Missing Value Analysis

Missing values occur when one or more observations do not contain a value for a particular feature.

Identifying missing values is an important step in Machine Learning because many algorithms cannot directly process missing observations.

Missing-value analysis will help determine:

- Whether missing values are present in the dataset.
- Which columns contain missing values.
- The number of missing values in each column.
- The percentage of missing values in each column.
- Whether any particular feature requires missing-value treatment.

The analysis will be performed on the complete dataset before any preprocessing or feature transformation.

The results will be calculated directly from the actual dataset using Python.

If no missing values are found, no imputation will be necessary for the corresponding columns.

If missing values are found, an appropriate treatment method will be selected during the preprocessing stage without using information from the test dataset.

In [13]:
# Checking missing values in all columns

missing_values = df.isnull().sum()

missing_table = pd.DataFrame({
    "Column": df.columns,
    "Missing Values": missing_values.values,
    "Missing Percentage": (missing_values.values / len(df) * 100).round(2)
})

display(missing_table)

print("Total missing values in the dataset:", df.isnull().sum().sum())

                        Column  Missing Values  Missing Percentage
0                     FILENAME               0                 0.0
1                          URL               0                 0.0
2                    URLLength               0                 0.0
3                       Domain               0                 0.0
4                 DomainLength               0                 0.0
5                   IsDomainIP               0                 0.0
6                          TLD               0                 0.0
7           URLSimilarityIndex               0                 0.0
8         CharContinuationRate               0                 0.0
9            TLDLegitimateProb               0                 0.0
10                 URLCharProb               0                 0.0
11                   TLDLength               0                 0.0
12               NoOfSubDomain               0                 0.0
13              HasObfuscation               0                 0.0
14          NoOfObfuscatedChar               0                 0.0
15            ObfuscationRatio               0                 0.0
16            NoOfLettersInURL               0                 0.0
17            LetterRatioInURL               0                 0.0
18             NoOfDegitsInURL               0                 0.0
19             DegitRatioInURL               0                 0.0
20             NoOfEqualsInURL               0                 0.0
21              NoOfQMarkInURL               0                 0.0
22          NoOfAmpersandInURL               0                 0.0
23  NoOfOtherSpecialCharsInURL               0                 0.0
24       SpacialCharRatioInURL               0                 0.0
25                     IsHTTPS               0                 0.0
26                  LineOfCode               0                 0.0
27           LargestLineLength               0                 0.0
28                    HasTitle               0                 0.0
29                       Title               0                 0.0
30       DomainTitleMatchScore               0                 0.0
31          URLTitleMatchScore               0                 0.0
32                  HasFavicon               0                 0.0
33                      Robots               0                 0.0
34                IsResponsive               0                 0.0
35             NoOfURLRedirect               0                 0.0
36            NoOfSelfRedirect               0                 0.0
37              HasDescription               0                 0.0
38                   NoOfPopup               0                 0.0
39                  NoOfiFrame               0                 0.0
40       HasExternalFormSubmit               0                 0.0
41                HasSocialNet               0                 0.0
42             HasSubmitButton               0                 0.0
43             HasHiddenFields               0                 0.0
44            HasPasswordField               0                 0.0
45                        Bank               0                 0.0
46                         Pay               0                 0.0
47                      Crypto               0                 0.0
48            HasCopyrightInfo               0                 0.0
49                   NoOfImage               0                 0.0
50                     NoOfCSS               0                 0.0
51                      NoOfJS               0                 0.0
52                 NoOfSelfRef               0                 0.0
53                NoOfEmptyRef               0                 0.0
54             NoOfExternalRef               0                 0.0
55                       label               0                 0.0

Total missing values in the dataset: 0

# 1.22 Missing Value Analysis — Interpretation

The missing-value analysis was performed on all 56 columns of the dataset.

The analysis shows that the dataset contains **no missing values**.

## Results

| Analysis | Result |
|---|---:|
| Total Records | 235,795 |
| Total Columns | 56 |
| Columns with Missing Values | 0 |
| Total Missing Values | 0 |

All analyzed columns have:

**0 missing values → 0.00% missing**

## Observations

### 1. No Missing Data

Every record contains a value for all 56 columns.

Therefore, there are no columns that require missing-value imputation at this stage.

### 2. No Imputation Required

Since there are no missing observations, techniques such as:

- Mean imputation
- Median imputation
- Mode imputation
- Forward filling
- Backward filling

are not required for this dataset.

### 3. Data Quality

The absence of missing values simplifies the preprocessing stage because the Machine Learning pipeline does not need a missing-value treatment step for the original dataset.

### 4. Future Preprocessing

Although the original dataset contains no missing values, preprocessing will still be performed carefully after separating the target and metadata columns.

Any transformations applied during later stages will be fitted only on the training data to prevent data leakage.

## Conclusion

The dataset contains **235,795 records and 56 columns with no missing values**.

Therefore:

**Missing-value treatment is not required for the original dataset.**

# 1.23 Duplicate Record Analysis

Duplicate records occur when two or more rows in a dataset contain exactly the same values across all columns.

Duplicate analysis is important because repeated observations can:

- Give excessive weight to the same record.
- Affect statistical analysis.
- Influence Machine Learning model training.
- Produce misleading evaluation results.

Therefore, duplicate records will be identified before the preprocessing stage.

This analysis will examine:

1. The total number of completely duplicated rows.
2. The percentage of duplicated rows.
3. Whether duplicate records are present in the dataset.

The analysis will be performed using the complete dataset before removing or modifying any records.

If duplicate rows are found, they will be handled carefully during preprocessing.

The actual number of duplicate records will be calculated directly from the dataset in the next code cell.

In [14]:
# Checking for completely duplicated rows

duplicate_count = df.duplicated().sum()
duplicate_percentage = (duplicate_count / len(df) * 100).round(2)

print("Total duplicate rows:", duplicate_count)
print("Duplicate percentage:", duplicate_percentage, "%")

if duplicate_count == 0:
    print("Conclusion: No completely duplicated rows were found.")
else:
    print("Conclusion: Duplicate rows are present in the dataset.")

Total duplicate rows: 0
Duplicate percentage: 0.0 %
Conclusion: No completely duplicated rows were found.

# 1.24 Duplicate Record Analysis — Interpretation

The duplicate-record analysis was performed across all 56 columns of the dataset.

## Results

| Analysis | Result |
|---|---:|
| Total Records | 235,795 |
| Total Columns | 56 |
| Completely Duplicate Rows | 0 |
| Duplicate Percentage | 0.00% |

## Observations

### 1. No Completely Duplicate Rows

The analysis found **0 completely duplicated rows**.

This means that no two records contain exactly the same values across all 56 columns.

### 2. No Duplicate-Row Removal Required

Since no completely duplicated rows were identified, there are no duplicate rows that need to be removed based on an exact full-row comparison.

Therefore, the current number of records remains:

**235,795 records**

### 3. URL-Level Duplication

Although no complete duplicate rows exist, different records may still contain the same URL while having differences in other columns.

Therefore, complete-row duplication and URL-level duplication are treated as separate analyses.

A separate URL duplication analysis will be performed to determine whether the `URL` column contains repeated URLs.

## Conclusion

The dataset contains **no completely duplicated records**.

Therefore, no rows will be removed based on full-row duplication at this stage.

# 1.25 URL-Level Duplicate Analysis

The previous analysis checked for completely identical rows across all 56 columns.

However, two records can contain the same URL while having different values in other columns.

Therefore, URL-level duplication must be analyzed separately.

This analysis will examine the `URL` column to determine:

- Total number of URL records.
- Number of unique URLs.
- Number of repeated URL records.
- Percentage of records associated with repeated URLs.
- Number of URLs that occur more than once.

## Why URL Duplication Matters

URL duplication is important in a phishing detection project because the same URL appearing in both training and testing data can potentially make model evaluation less representative of performance on genuinely unseen URLs.

For this reason, URL-level duplication will be investigated before the final train-test splitting strategy is established.

The analysis will not remove records automatically.

First, the actual duplication pattern will be measured using the dataset.

The results will then be used to determine whether special handling is required during preprocessing and dataset splitting.

In [16]:
# Analyzing URL-level duplication

total_urls = len(df)

unique_urls = df["URL"].nunique()

duplicate_url_records = total_urls - unique_urls

duplicate_url_percentage = round(
    duplicate_url_records / total_urls * 100, 2
)

url_frequency = df["URL"].value_counts()

repeated_url_count = (url_frequency > 1).sum()

print("Total URL records:", total_urls)
print("Unique URLs:", unique_urls)
print("Repeated URL records:", duplicate_url_records)
print("Repeated URL record percentage:", duplicate_url_percentage, "%")
print("Number of URLs occurring more than once:", repeated_url_count)

Total URL records: 235795
Unique URLs: 235370
Repeated URL records: 425
Repeated URL record percentage: 0.18 %
Number of URLs occurring more than once: 425

# 1.26 URL-Level Duplicate Analysis — Interpretation

The URL-level duplication analysis was performed separately from the complete-row duplicate analysis.

The actual results are:

| Analysis | Result |
|---|---:|
| Total URL Records | 235,795 |
| Unique URLs | 235,370 |
| Repeated URL Records | 425 |
| Repeated URL Record Percentage | 0.18% |
| URLs Occurring More Than Once | 425 |

## Observations

### 1. High URL Uniqueness

The dataset contains **235,370 unique URLs** out of 235,795 total URL records.

This indicates that the large majority of URL records are unique.

### 2. Repeated URLs

There are **425 repeated URL records**, representing approximately **0.18%** of all records.

Therefore, URL repetition is present but represents a small portion of the complete dataset.

### 3. Difference Between Row and URL Duplication

The complete-row duplicate analysis found:

**0 completely duplicated rows**

The URL-level analysis found:

**425 repeated URL records**

This difference occurs because records can share the same URL while having different values in other columns.

### 4. Machine Learning Consideration

Repeated URLs are relevant when designing the train-test evaluation strategy.

If the same URL appears in both training and testing data, the model may be evaluated on an input that it has already encountered during training.

Therefore, URL duplication should be considered when designing the final data-splitting strategy.

The project will preserve the original dataset at this stage and will document the final handling strategy during preprocessing.

## Conclusion

The dataset contains a very high proportion of unique URLs, with only **0.18% of URL records associated with repeated URLs**.

No automatic URL-based record removal is performed at this stage.

Further preprocessing decisions will be made after examining the remaining dataset characteristics.

# 1.27 Constant Feature Analysis

A constant feature is a feature that contains the same value for every record in the dataset.

Constant features do not provide variation between observations and therefore cannot help a Machine Learning model distinguish between different classes.

Identifying constant features is important because removing them can:

- Reduce unnecessary features.
- Simplify the dataset.
- Reduce computational requirements.
- Avoid including variables that contain no predictive variation.

This analysis will examine the predictive and metadata columns to determine whether any feature has only one unique value.

The target variable `label` will be excluded from the constant-feature check because it is the output variable rather than a predictive feature.

The actual number of unique values for each feature will be calculated directly from the dataset in the next code cell.

In [17]:
# Identifying constant features

feature_columns = df.drop(columns=["label"]).columns

unique_counts = df[feature_columns].nunique()

constant_features = unique_counts[unique_counts == 1]

print("Number of constant features:", len(constant_features))

if len(constant_features) == 0:
    print("No constant features were found.")
else:
    print("\nConstant features:")
    display(constant_features.to_frame(name="Unique Values"))

Number of constant features: 0
No constant features were found.

# 1.28 Constant Feature Analysis — Interpretation

The constant-feature analysis was performed on the dataset after excluding the target variable `label`.

## Result

| Analysis | Result |
|---|---:|
| Features examined | 55 |
| Constant features | 0 |

## Observations

### 1. No Constant Features

The analysis found **0 constant features**.

Therefore, none of the examined features contains only a single unique value across all 235,795 records.

### 2. No Constant-Feature Removal Required

Since every examined feature contains variation, no feature needs to be removed because of zero variance at this stage.

### 3. Importance for Machine Learning

Features with no variation cannot provide useful information for distinguishing between classes.

Since no constant features were found, all non-target columns remain candidates for further analysis.

However, this does not mean that every feature will necessarily be used in the final Machine Learning model.

Features may later be excluded or selected based on:

- Data type
- Cardinality
- Correlation
- Predictive relevance
- Redundancy
- Feature-selection techniques
- Model requirements

## Conclusion

The dataset contains **no constant features** among the 55 non-target columns examined.

Therefore, no features will be removed based on constant-value analysis.

# 1.29 Descriptive Statistical Analysis

Descriptive statistics provide a numerical summary of the dataset.

They help us understand the distribution and range of numerical features before applying Machine Learning algorithms.

The analysis will examine important statistical measures such as:

- Count
- Mean
- Standard deviation
- Minimum value
- First quartile (25%)
- Median (50%)
- Third quartile (75%)
- Maximum value

## Why Descriptive Statistics Are Important

Descriptive statistics help identify:

1. The typical value of a feature.
2. The amount of variation in a feature.
3. The range of feature values.
4. Potentially unusual or extreme observations.
5. Differences in the scale of different numerical features.

## Numerical Feature Analysis

The dataset contains numerical features representing different URL and webpage characteristics.

These features will be analyzed using statistical summaries generated directly from the dataset.

The target variable `label` will be analyzed separately because it represents the classification output rather than a continuous predictive feature.

## Interpretation

The statistical summary will be used to understand the original feature distributions and to identify whether scaling or additional preprocessing may be appropriate.

No feature will be removed solely based on descriptive statistics.

Further decisions will be made using exploratory data analysis and feature-selection techniques.

In [18]:
# Generating descriptive statistics for numerical features

numerical_columns = df.select_dtypes(include=["int64", "float64"]).columns.tolist()

# Exclude the target variable from the predictive feature statistics
numerical_features = [column for column in numerical_columns if column != "label"]

descriptive_statistics = df[numerical_features].describe().T

display(descriptive_statistics)

,count,mean,std,min,25%,50%,75%,max
URLLength,235795.0,34.573095,41.314153,13.000000,23.000000,27.000000,34.000000,6.097000e+03
DomainLength,235795.0,21.470396,9.150793,4.000000,16.000000,20.000000,24.000000,1.100000e+02
IsDomainIP,235795.0,0.002706,0.051946,0.000000,0.000000,0.000000,0.000000,1.000000e+00
URLSimilarityIndex,235795.0,78.430778,28.976055,0.155574,57.024793,100.000000,100.000000,1.000000e+02
CharContinuationRate,235795.0,0.845508,0.216632,0.000000,0.680000,1.000000,1.000000,1.000000e+00
TLDLegitimateProb,235795.0,0.260423,0.251628,0.000000,0.005977,0.079963,0.522907,5.229071e-01
URLCharProb,235795.0,0.055747,0.010587,0.001083,0.050747,0.057970,0.062875,9.082366e-02
TLDLength,235795.0,2.764456,0.599739,2.000000,2.000000,3.000000,3.000000,1.300000e+01
NoOfSubDomain,235795.0,1.164758,0.600969,0.000000,1.000000,1.000000,1.000000,1.000000e+01
HasObfuscation,235795.0,0.002057,0.045306,0.000000,0.000000,0.000000,0.000000,1.000000e+00
NoOfObfuscatedChar,235795.0,0.024861,1.876249,0.000000,0.000000,0.000000,0.000000,4.470000e+02
ObfuscationRatio,235795.0,0.000138,0.003817,0.000000,0.000000,0.000000,0.000000,3.480000e-01
NoOfLettersInURL,235795.0,19.428919,29.090330,0.000000,10.000000,14.000000,20.000000,5.191000e+03
LetterRatioInURL,235795.0,0.515946,0.123315,0.000000,0.435000,0.519000,0.594000,9.260000e-01
NoOfDegitsInURL,235795.0,1.881011,11.886695,0.000000,0.000000,0.000000,0.000000,2.011000e+03
DegitRatioInURL,235795.0,0.028616,0.070897,0.000000,0.000000,0.000000,0.000000,6.840000e-01
NoOfEqualsInURL,235795.0,0.062241,0.934704,0.000000,0.000000,0.000000,0.000000,1.760000e+02
NoOfQMarkInURL,235795.0,0.029403,0.193505,0.000000,0.000000,0.000000,0.000000,4.000000e+00
NoOfAmpersandInURL,235795.0,0.025056,0.836448,0.000000,0.000000,0.000000,0.000000,1.490000e+02
NoOfOtherSpecialCharsInURL,235795.0,2.340198,3.527603,0.000000,1.000000,1.000000,3.000000,4.990000e+02
SpacialCharRatioInURL,235795.0,0.063309,0.032393,0.000000,0.038000,0.050000,0.083000,3.970000e-01
IsHTTPS,235795.0,0.782625,0.412461,0.000000,1.000000,1.000000,1.000000,1.000000e+00
LineOfCode,235795.0,1141.900443,3419.950513,2.000000,18.000000,429.000000,1277.000000,4.426660e+05
LargestLineLength,235795.0,12789.532624,152201.099228,22.000000,200.000000,1090.000000,8047.000000,1.397573e+07
HasTitle,235795.0,0.861261,0.345675,0.000000,1.000000,1.000000,1.000000,1.000000e+00
DomainTitleMatchScore,235795.0,50.131427,49.676981,0.000000,0.000000,75.000000,100.000000,1.000000e+02
URLTitleMatchScore,235795.0,52.122098,49.600564,0.000000,0.000000,100.000000,100.000000,1.000000e+02
HasFavicon,235795.0,0.361768,0.480513,0.000000,0.000000,0.000000,1.000000,1.000000e+00
Robots,235795.0,0.266541,0.442151,0.000000,0.000000,0.000000,1.000000,1.000000e+00
IsResponsive,235795.0,0.624513,0.484249,0.000000,0.000000,1.000000,1.000000,1.000000e+00
NoOfURLRedirect,235795.0,0.133438,0.340048,0.000000,0.000000,0.000000,0.000000,1.000000e+00
NoOfSelfRedirect,235795.0,0.040107,0.196210,0.000000,0.000000,0.000000,0.000000,1.000000e+00
HasDescription,235795.0,0.440183,0.496410,0.000000,0.000000,0.000000,1.000000,1.000000e+00
NoOfPopup,235795.0,0.221765,3.870540,0.000000,0.000000,0.000000,0.000000,6.020000e+02
NoOfiFrame,235795.0,1.588638,5.762561,0.000000,0.000000,0.000000,1.000000,1.602000e+03
HasExternalFormSubmit,235795.0,0.043987,0.205067,0.000000,0.000000,0.000000,0.000000,1.000000e+00
HasSocialNet,235795.0,0.456570,0.498111,0.000000,0.000000,0.000000,1.000000,1.000000e+00
HasSubmitButton,235795.0,0.414301,0.492602,0.000000,0.000000,0.000000,1.000000,1.000000e+00
HasHiddenFields,235795.0,0.377799,0.484838,0.000000,0.000000,0.000000,1.000000,1.000000e+00
HasPasswordField,235795.0,0.102263,0.302994,0.000000,0.000000,0.000000,0.000000,1.000000e+00
Bank,235795.0,0.127089,0.333074,0.000000,0.000000,0.000000,0.000000,1.000000e+00
Pay,235795.0,0.237007,0.425247,0.000000,0.000000,0.000000,0.000000,1.000000e+00
Crypto,235795.0,0.023474,0.151403,0.000000,0.000000,0.000000,0.000000,1.000000e+00
HasCopyrightInfo,235795.0,0.486775,0.499826,0.000000,0.000000,0.000000,1.000000,1.000000e+00
NoOfImage,235795.0,26.075689,79.411815,0.000000,0.000000,8.000000,29.000000,8.956000e+03
NoOfCSS,235795.0,6.333111,74.866296,0.000000,0.000000,2.000000,8.000000,3.582000e+04
NoOfJS,235795.0,10.522305,22.312192,0.000000,0.000000,6.000000,15.000000,6.957000e+03
NoOfSelfRef,235795.0,65.071113,176.687539,0.000000,0.000000,12.000000,88.000000,2.739700e+04
NoOfEmptyRef,235795.0,2.377629,17.641097,0.000000,0.000000,0.000000,1.000000,4.887000e+03
NoOfExternalRef,235795.0,49.262516,161.027430,0.000000,1.000000,10.000000,57.000000,2.751600e+04

# 1.30 Descriptive Statistics — Interpretation

The descriptive statistical analysis was performed on the numerical predictive features while excluding the target variable `label`.

The generated table contains the following statistical measures:

- Count
- Mean
- Standard deviation
- Minimum
- 25th percentile
- Median
- 75th percentile
- Maximum

## 1. Complete Numerical Observations

The `count` value for the displayed numerical features is **235,795**.

This is consistent with the total number of records in the dataset and confirms that the numerical features do not contain missing observations.

## 2. Feature Scale Differences

The numerical features have substantially different value ranges.

For example:

- `URLLength` ranges from **13** to approximately **6,097**.
- `DomainLength` ranges from **4** to approximately **1,100**.
- `TLDLength` ranges from **2** to **13**.
- `NoOfLettersInURL` ranges from **0** to approximately **5,191**.
- `NoOfDigitsInURL` ranges from **0** to approximately **2,011**.
- `LineOfCode` has a considerably larger numerical range than several other features.
- Probability and ratio features generally have much smaller numerical ranges.

These differences demonstrate that the numerical features are measured on different scales.

## 3. Measures of Central Tendency

The `mean` and `50%` columns provide information about the central tendency of each feature.

The difference between the mean and median can provide an indication that a feature may have an asymmetric distribution.

For example, some count-based URL features have means that differ considerably from their medians, suggesting that their distributions should be examined further during Exploratory Data Analysis.

## 4. Feature Variability

The `std` column represents the standard deviation of each feature.

Features with larger standard deviations show greater variation in their values, while smaller standard deviations indicate that observations are more concentrated around their mean.

The variation differs considerably across the numerical features.

## 5. Range and Extreme Values

The difference between the minimum and maximum values indicates the overall range of a feature.

Some features have relatively small ranges, while others have very large maximum values.

These differences indicate that certain features may contain highly dispersed or extreme observations.

Such distributions will be investigated further using visualization techniques during Exploratory Data Analysis.

## 6. Implication for Preprocessing

Because the numerical features have different scales, feature scaling may be appropriate for Machine Learning algorithms that are sensitive to feature magnitude.

The choice of scaling method will be determined during the preprocessing stage based on the selected models.

Tree-based algorithms generally do not require feature scaling, whereas distance-based and gradient-based algorithms can be affected by differences in feature scale.

## 7. No Feature Removed at This Stage

Descriptive statistics alone will not be used to automatically remove features.

Potentially important features will be examined further using:

- Distribution analysis
- Correlation analysis
- Feature-selection techniques
- Model-based importance
- Redundancy analysis

## Conclusion

The descriptive statistics show that the numerical features contain complete observations but have substantially different distributions, ranges, and scales.

This analysis provides a foundation for the upcoming Exploratory Data Analysis and preprocessing stages.

In [19]:
# Analyzing the skewness of numerical features

skewness = df[numerical_features].skew().sort_values(ascending=False)

skewness_table = pd.DataFrame({
    "Feature": skewness.index,
    "Skewness": skewness.values.round(4)
})

display(skewness_table)

print("Number of numerical features analyzed:", len(numerical_features))

                       Feature  Skewness
0                      NoOfCSS  464.4040
1           NoOfObfuscatedChar  204.6843
2                       NoOfJS  140.4358
3              NoOfEqualsInURL  114.9855
4                 NoOfEmptyRef  106.8262
5           NoOfAmpersandInURL  106.7173
6                   NoOfiFrame   97.6773
7              NoOfDegitsInURL   94.8776
8                    NoOfPopup   84.9527
9              NoOfExternalRef   65.9002
10                 NoOfSelfRef   60.3814
11            NoOfLettersInURL   58.4026
12                   URLLength   53.3217
13                  LineOfCode   53.0723
14           LargestLineLength   48.1799
15  NoOfOtherSpecialCharsInURL   47.4285
16            ObfuscationRatio   40.1186
17                   NoOfImage   28.2303
18              HasObfuscation   21.9814
19                  IsDomainIP   19.1466
20              NoOfQMarkInURL    8.1606
21                      Crypto    6.2949
22            NoOfSelfRedirect    4.6878
23       HasExternalFormSubmit    4.4475
24             DegitRatioInURL    3.2445
25            HasPasswordField    2.6254
26                DomainLength    2.5134
27                        Bank    2.2392
28             NoOfURLRedirect    2.1560
29               NoOfSubDomain    1.8094
30                   TLDLength    1.6635
31                         Pay    1.2369
32       SpacialCharRatioInURL    1.1841
33                      Robots    1.0560
34                  HasFavicon    0.5754
35             HasHiddenFields    0.5041
36             HasSubmitButton    0.3479
37              HasDescription    0.2410
38                HasSocialNet    0.1744
39           TLDLegitimateProb    0.0731
40            HasCopyrightInfo    0.0529
41       DomainTitleMatchScore   -0.0087
42            LetterRatioInURL   -0.0664
43          URLTitleMatchScore   -0.0891
44                IsResponsive   -0.5143
45          URLSimilarityIndex   -0.9899
46                 URLCharProb   -1.0643
47        CharContinuationRate   -1.1286
48                     IsHTTPS   -1.3704
49                    HasTitle   -2.0902

Number of numerical features analyzed: 50

# 1.31 Skewness Analysis — Interpretation

Skewness was calculated for the numerical predictive features to understand the shape of their distributions.

## Observations

The analysis shows that several numerical features have high positive skewness.

Examples from the dataset include:

| Feature | Skewness |
|---|---:|
| `NoOfCSS` | 464.0440 |
| `NoOfObfuscatedChar` | 264.0843 |
| `NoOfJS` | 140.4358 |
| `NoOfEqualsInURL` | 114.9855 |
| `NoOfEmptyRef` | 106.8262 |
| `NoOfAmpersandInURL` | 106.7173 |
| `NoOfIframe` | 97.6773 |
| `NoOfDigitsInURL` | 94.8776 |

## Interpretation

High positive skewness indicates that the distribution has a long right-hand tail.

This pattern is common in count-based website features because many observations may have relatively small values while a smaller number of observations can have substantially larger values.

For example, features such as the number of CSS elements, JavaScript elements, digits, references, or special characters can have many low values and a smaller number of unusually high values.

## Important Consideration

High skewness does not automatically mean that a feature is invalid or should be removed.

A skewed feature may still contain useful information for distinguishing phishing and legitimate websites.

Therefore, these features will be retained for further analysis at this stage.

During preprocessing and model development, the need for transformations such as logarithmic transformation or robust scaling will be considered based on the requirements of the selected Machine Learning algorithms.

## Relationship with Exploratory Data Analysis

The skewness results provide an indication of which features may require closer examination during Exploratory Data Analysis.

Distribution plots and box plots will be used later to visually examine important numerical features and identify potential extreme observations.

## Conclusion

The numerical features show substantial differences in distribution shape, with several count-based features exhibiting strong positive skewness.

This observation will be considered during preprocessing and model development, but no features are removed solely because of skewness.

# 1.32 Dataset Description — Overall Summary

The dataset description and initial analysis have provided an understanding of the structure, quality, and characteristics of the PhiUSIIL Phishing URL dataset.

## Dataset Summary

| Property | Result |
|---|---:|
| Dataset | PhiUSIIL Phishing URL (Website) Dataset |
| Total Records | 235,795 |
| Total Columns | 56 |
| Predictive Features | 54 |
| Metadata Column | `FILENAME` |
| Target Variable | `label` |
| Target Classes | 2 |
| Phishing Records | 100,945 (42.81%) |
| Legitimate Records | 134,850 (57.19%) |
| Integer Columns | 41 |
| Floating-Point Columns | 10 |
| Text/Object Columns | 5 |
| Total Missing Values | 0 |
| Completely Duplicate Rows | 0 |
| Unique URLs | 235,370 |
| Repeated URL Records | 425 (0.18%) |
| Constant Features | 0 |

## Key Findings

### 1. Dataset Size

The dataset contains **235,795 records and 56 columns**, providing a substantial number of observations for binary classification.

### 2. Target Variable

The target variable is `label`.

The target classes are:

- `0` — Phishing
- `1` — Legitimate

The dataset contains both classes in substantial quantities.

### 3. Data Quality

The dataset contains **no missing values** and **no completely duplicated rows**.

Therefore, no missing-value imputation or full-row duplicate removal is required for the original dataset.

### 4. URL Duplication

There are **425 repeated URL records**, representing approximately **0.18%** of all records.

Although complete duplicate rows were not found, URL-level duplication will be considered when designing the train-test splitting strategy.

### 5. Text and Metadata Features

The five text/object columns are:

- `FILENAME`
- `URL`
- `Domain`
- `TLD`
- `Title`

`FILENAME` is treated as metadata.

`URL`, `Domain`, and `Title` have high cardinality and therefore require careful treatment.

`TLD` has comparatively lower cardinality and will be examined further before selecting an encoding approach.

### 6. Numerical Features

The dataset contains:

- **41 integer columns**
- **10 floating-point columns**

The numerical features represent different URL and webpage characteristics.

The descriptive-statistics analysis showed substantial differences in their ranges and scales.

### 7. Feature Distribution

Several numerical count-based features exhibit strong positive skewness.

For example, `NoOfCSS`, `NoOfObfuscatedChar`, `NoOfJS`, and `NoOfDigitsInURL` show high positive skewness.

This does not automatically mean that these features should be removed. Their distributions will be examined further during Exploratory Data Analysis.

## Preparation for the Next Stage

The findings from this dataset analysis will guide the preprocessing stage.

The preprocessing workflow will include:

1. Separating the target variable.
2. Removing metadata that should not be used as a predictive feature.
3. Examining text and categorical features.
4. Selecting appropriate predictive features.
5. Applying suitable categorical encoding where required.
6. Applying feature scaling where required.
7. Designing an appropriate train-test splitting strategy.
8. Preventing data leakage during preprocessing and model training.

## Conclusion

The initial dataset analysis establishes that the PhiUSIIL dataset is a large binary classification dataset containing numerical, categorical, and text-based information.

The dataset contains no missing values, no completely duplicated rows, and no constant features.

The observed differences in feature scale, skewness, and text-feature cardinality will be considered during the subsequent preprocessing and Exploratory Data Analysis stages.

In [20]:
# Final verification of the dataset description

print("FINAL DATASET VERIFICATION")
print("-" * 40)

print("Dataset records:", len(df))
print("Total columns:", len(df.columns))
print("Predictive features:", len(df.columns) - 2)
print("Metadata column:", "FILENAME")
print("Target variable:", "label")

print("\nTarget classes:")
print(df["label"].value_counts().sort_index())

print("\nMissing values:", df.isnull().sum().sum())
print("Completely duplicated rows:", df.duplicated().sum())

print("\nUnique URLs:", df["URL"].nunique())
print("Constant features:", len(constant_features))

print("\nDataset verification completed successfully.")

FINAL DATASET VERIFICATION
----------------------------------------
Dataset records: 235795
Total columns: 56
Predictive features: 54
Metadata column: FILENAME
Target variable: label

Target classes:
label
0    100945
1    134850
Name: count, dtype: int64

Missing values: 0
Completely duplicated rows: 0

Unique URLs: 235370
Constant features: 0

Dataset verification completed successfully.

# 1.33 Notebook 01 — Final Conclusion

## Dataset Description and Initial Understanding

This notebook completed the initial analysis of the **PhiUSIIL Phishing URL (Website) Dataset**.

The dataset contains **235,795 records and 56 columns**.

The analysis examined the dataset structure, feature names, data types, target variable, class distribution, cardinality, missing values, duplicate records, URL-level duplication, constant features, descriptive statistics, and numerical feature skewness.

## Final Dataset Findings

### Dataset Structure

- Total records: **235,795**
- Total columns: **56**
- Predictive features according to the dataset documentation: **54**
- Metadata column: **`FILENAME`**
- Target variable: **`label`**

### Target Distribution

The target variable contains two classes:

- **Label 0 — Phishing:** 100,945 records (42.81%)
- **Label 1 — Legitimate:** 134,850 records (57.19%)

### Data Types

The dataset contains:

- **41 integer columns**
- **10 floating-point columns**
- **5 text/object columns**

### Data Quality

The analysis found:

- **0 missing values**
- **0 completely duplicated rows**
- **0 constant features**

Therefore, the original dataset does not require missing-value imputation or complete duplicate-row removal.

### URL-Level Duplication

The analysis identified:

- **235,370 unique URLs**
- **425 repeated URL records**
- **0.18% repeated URL records**

URL-level duplication will be considered when designing the train-test splitting strategy.

### Text/Object Features

The five text/object columns are:

- `FILENAME`
- `URL`
- `Domain`
- `TLD`
- `Title`

`FILENAME` is treated as metadata and will not be used as a predictive feature.

`URL`, `Domain`, and `Title` have high cardinality and therefore should not automatically be converted into large one-hot encoded feature spaces.

`TLD` has comparatively lower cardinality and will be examined further during preprocessing.

### Numerical Features

The dataset contains 51 numerical columns, including the target variable.

After excluding the target variable, the numerical predictive features consist of:

- **40 integer features**
- **10 floating-point features**

The numerical features have different ranges and scales.

Several count-based features also exhibit strong positive skewness.

These characteristics will be considered during preprocessing and exploratory analysis.

## Data Leakage Prevention

The Machine Learning pipeline will be designed to avoid data leakage.

The following principles will be followed:

1. The target variable will be separated from the predictors.
2. Metadata will be excluded from the predictive feature matrix.
3. The dataset will be split before fitting learned preprocessing operations.
4. Preprocessing parameters will be learned using training data only.
5. Test data will only be transformed using parameters learned from training data.
6. Feature-selection procedures will avoid using the final test set.
7. Hyperparameter tuning will use cross-validation on the training data.
8. The final test set will remain isolated until final model evaluation.

## Transition to Data Preprocessing

The dataset has now been examined sufficiently for the Dataset Description stage.

The next notebook will focus on **Data Preprocessing**.

The preprocessing stage will prepare the dataset for Machine Learning by addressing:

- Metadata removal
- Target separation
- Feature-type handling
- Categorical/text feature treatment
- Feature scaling where required
- Train-test splitting
- Duplicate handling where appropriate
- Data leakage prevention
- Final feature matrix preparation

## Final Conclusion

The initial dataset analysis provides a clear understanding of the dataset structure and data quality.

The dataset contains a large number of labelled observations, no missing values, no completely duplicated rows, and no constant features.

The differences in feature scale, skewness, and text-feature cardinality will guide the preprocessing and Machine Learning stages of the phishing URL detection project.