# 09 — Final Prediction and Phishing URL Classification

## Project: Phishing URL Detection Using Machine Learning

### Objective

The objective of this notebook is to use the trained machine learning models to perform final predictions on unseen URL records.

The system classifies each URL record into one of two classes:

- **0 → Phishing**
- **1 → Legitimate**

### Final Prediction Workflow

1. Load the selected-feature dataset.
2. Load the trained machine learning models.
3. Load the required feature scaler.
4. Identify the final model based on the evaluation results.
5. Prepare unseen/sample input data.
6. Generate the predicted class.
7. Calculate the prediction probability.
8. Display and interpret the final prediction.

### Input

The prediction system uses the **40 selected numerical features** obtained during feature selection.

The target variable (`label`) is not provided as an input during prediction.

### Output

For each input record, the system will display:

- Predicted class
- Predicted class name
- Prediction probability
- Final interpretation as **Phishing** or **Legitimate**

### Expected Result

This notebook demonstrates the practical use of the trained phishing URL detection model for classifying previously unseen URL records.

In [1]:
# Import required libraries

import pandas as pd
import numpy as np
import joblib

print("FINAL PREDICTION ENVIRONMENT")
print("=" * 60)

# Load the selected-feature dataset
df = pd.read_csv("../dataset/PhiUSIIL_Selected_Features.csv")

print("Dataset loaded successfully.")
print("Dataset shape:", df.shape)
print("Number of records:", len(df))
print("Number of selected features:", len(df.columns) - 1)
print("Target column: label")

print("\nFirst 5 records:")
display(df.head())

print("\n✅ Dataset loaded successfully.")

FINAL PREDICTION ENVIRONMENT
============================================================
Dataset loaded successfully.
Dataset shape: (235795, 41)
Number of records: 235795
Number of selected features: 40
Target column: label

First 5 records:

,URLSimilarityIndex,HasSocialNet,WebStructureScore,HasDescription,HasCopyrightInfo,DomainTitleMatchScore,NoOfSelfRef,NoOfExternalRef,IsHTTPS,NoOfImage,...,DomainLength,NoOfDegitsInURL,URLDomainLengthRatio,NoOfiFrame,NoOfCSS,Pay,CSSDensity,TotalReferenceDensity,Robots,label
0,100.0,0,4,0,1,0.000000,119,124,1,34,...,24,0,1.291667,1,20,0,0.035842,0.435484,1,1
1,100.0,1,3,0,1,55.555556,39,217,1,50,...,16,0,1.437500,0,9,0,0.014563,0.414239,1,1
2,100.0,0,5,1,1,46.666667,42,5,1,10,...,22,0,1.318182,0,2,0,0.004283,0.104925,1,1
3,100.0,1,4,0,1,0.000000,22,31,1,3,...,19,0,1.368421,12,27,1,0.004248,0.008496,1,1
4,100.0,1,5,1,1,100.000000,72,85,1,244,...,26,0,1.269231,2,15,1,0.002463,0.025948,1,1

✅ Dataset loaded successfully.

In [2]:
# Load trained models and feature scaler

logistic_model = joblib.load("../models/logistic_regression_tuned.pkl")
decision_tree_model = joblib.load("../models/decision_tree_tuned.pkl")
random_forest_model = joblib.load("../models/random_forest_tuned.pkl")

scaler = joblib.load("../models/tuning_feature_scaler.pkl")

# Store models in a dictionary
models = {
    "Logistic Regression": logistic_model,
    "Decision Tree": decision_tree_model,
    "Random Forest": random_forest_model
}

print("TRAINED MODELS LOADED")
print("=" * 60)

for model_name, model in models.items():
    print(f"✓ {model_name}: {type(model).__name__}")

print("\n✓ Feature scaler loaded:", type(scaler).__name__)
print("✓ Total models loaded:", len(models))

TRAINED MODELS LOADED
============================================================
✓ Logistic Regression: LogisticRegression
✓ Decision Tree: DecisionTreeClassifier
✓ Random Forest: RandomForestClassifier

✓ Feature scaler loaded: StandardScaler
✓ Total models loaded: 3

In [3]:
# Separate input features and target variable

X = df.drop(columns=["label"])
y = df["label"]

print("FINAL PREDICTION DATA PREPARATION")
print("=" * 60)

print("Input feature shape:", X.shape)
print("Target shape:", y.shape)

print("\nNumber of input features:", X.shape[1])
print("Target classes:", sorted(y.unique()))

print("\nFeature verification:")
print("Missing values:", X.isnull().sum().sum())
print("Duplicate feature names:", X.columns.duplicated().sum())

print("\n✅ Prediction features prepared successfully.")

FINAL PREDICTION DATA PREPARATION
============================================================
Input feature shape: (235795, 40)
Target shape: (235795,)

Number of input features: 40
Target classes: [np.int64(0), np.int64(1)]

Feature verification:
Missing values: 0
Duplicate feature names: 0

✅ Prediction features prepared successfully.

In [4]:
# Select sample records for final prediction demonstration

# Use records from the dataset only for demonstration.
# The label is kept separately so that we can compare
# the model prediction with the actual class afterward.

sample_size = 10

sample_data = df.sample(
    n=sample_size,
    random_state=100
)

X_sample = sample_data.drop(columns=["label"])
y_actual = sample_data["label"]

print("SAMPLE DATA PREPARED")
print("=" * 60)

print("Number of sample records:", len(X_sample))
print("Number of input features:", X_sample.shape[1])

print("\nActual classes of selected records:")
print(y_actual.to_numpy())

print("\nInput feature data:")
display(X_sample)

print("\n✅ Sample prediction data prepared.")

SAMPLE DATA PREPARED
============================================================
Number of sample records: 10
Number of input features: 40

Actual classes of selected records:
[0 1 1 1 0 0 1 0 1 1]

Input feature data:

,URLSimilarityIndex,HasSocialNet,WebStructureScore,HasDescription,HasCopyrightInfo,DomainTitleMatchScore,NoOfSelfRef,NoOfExternalRef,IsHTTPS,NoOfImage,...,HasHiddenFields,DomainLength,NoOfDegitsInURL,URLDomainLengthRatio,NoOfiFrame,NoOfCSS,Pay,CSSDensity,TotalReferenceDensity,Robots
24544,34.327230,0,2,0,0,0.0,0,3,1,0,...,0,33,4,1.242424,0,0,0,0.000000,0.027778,0
181718,100.000000,1,5,1,1,100.0,108,116,1,31,...,1,13,0,1.538462,4,29,0,0.031590,0.250545,1
145963,100.000000,1,3,1,1,0.0,73,90,1,9,...,0,23,0,1.304348,1,18,0,0.036437,0.329960,1
72470,100.000000,0,5,1,1,100.0,206,206,1,2,...,1,22,0,1.318182,0,7,0,0.004510,0.266753,0
46220,17.881364,0,4,1,1,0.0,1,3,1,20,...,0,27,5,2.370370,0,8,0,0.013986,0.036713,0
111363,75.091912,0,1,0,0,100.0,1,1,0,0,...,0,15,0,1.400000,0,0,0,0.000000,0.400000,0
60250,100.000000,0,7,1,1,0.0,0,31,1,10,...,1,28,0,1.250000,0,11,0,0.007931,0.028118,1
195455,56.755515,0,1,0,0,0.0,0,0,0,0,...,0,20,0,1.300000,0,0,0,0.000000,0.000000,0
81617,100.000000,1,4,1,1,0.0,84,33,1,53,...,1,22,0,1.318182,1,11,0,0.009735,0.103540,0
62535,100.000000,0,2,1,1,0.0,22,8,1,13,...,0,15,0,1.466667,0,4,0,0.023529,0.176471,0

✅ Sample prediction data prepared.

In [5]:
# Generate predictions for the sample records using all trained models

predictions = {}
probabilities = {}

# Scale sample data for models trained with StandardScaler
X_sample_scaled = scaler.transform(X_sample)

for model_name, model in models.items():

    if model_name == "Random Forest":
        # Random Forest was trained using unscaled features
        X_input = X_sample
    else:
        # Logistic Regression and Decision Tree use scaled features
        X_input = X_sample_scaled

    # Predicted class
    y_pred = model.predict(X_input)

    # Prediction probability
    y_prob = model.predict_proba(X_input)

    predictions[model_name] = y_pred

    # Probability of the predicted class
    probabilities[model_name] = np.max(y_prob, axis=1)

print("FINAL PREDICTIONS GENERATED")
print("=" * 60)

for model_name in models:
    print(f"✓ {model_name}: {len(predictions[model_name])} predictions")

print("\n✅ Predictions generated successfully.")

FINAL PREDICTIONS GENERATED
============================================================
✓ Logistic Regression: 10 predictions
✓ Decision Tree: 10 predictions
✓ Random Forest: 10 predictions

✅ Predictions generated successfully.

c:\Users\Hitesh\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
c:\Users\Hitesh\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
c:\Users\Hitesh\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
c:\Users\Hitesh\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

In [6]:
# Create a final prediction results table

prediction_results = pd.DataFrame({
    "Record": range(1, len(X_sample) + 1),
    "Actual Class": y_actual.to_numpy(),
    "Logistic Regression": predictions["Logistic Regression"],
    "Decision Tree": predictions["Decision Tree"],
    "Random Forest": predictions["Random Forest"]
})

# Convert numerical labels into readable class names
class_mapping = {
    0: "Phishing",
    1: "Legitimate"
}

prediction_results["Actual Class"] = (
    prediction_results["Actual Class"].map(class_mapping)
)

for model_name in models:
    prediction_results[model_name] = (
        prediction_results[model_name].map(class_mapping)
    )

print("FINAL PREDICTION RESULTS")
print("=" * 60)

display(prediction_results)

print("\nClass Mapping:")
print("0 → Phishing")
print("1 → Legitimate")

print("\n✅ Final prediction table generated.")

FINAL PREDICTION RESULTS
============================================================

   Record Actual Class Logistic Regression Decision Tree Random Forest
0       1     Phishing            Phishing      Phishing      Phishing
1       2   Legitimate          Legitimate    Legitimate    Legitimate
2       3   Legitimate          Legitimate    Legitimate    Legitimate
3       4   Legitimate          Legitimate    Legitimate    Legitimate
4       5     Phishing            Phishing      Phishing      Phishing
5       6     Phishing            Phishing      Phishing      Phishing
6       7   Legitimate          Legitimate    Legitimate    Legitimate
7       8     Phishing            Phishing      Phishing      Phishing
8       9   Legitimate          Legitimate    Legitimate    Legitimate
9      10   Legitimate          Legitimate    Legitimate    Legitimate

Class Mapping:
0 → Phishing
1 → Legitimate

✅ Final prediction table generated.

In [7]:
# Display prediction probabilities for each model

probability_results = pd.DataFrame({
    "Record": range(1, len(X_sample) + 1),
    "Actual Class": y_actual.map(class_mapping).to_numpy(),
    "Logistic Regression Probability": probabilities["Logistic Regression"],
    "Decision Tree Probability": probabilities["Decision Tree"],
    "Random Forest Probability": probabilities["Random Forest"]
})

print("PREDICTION PROBABILITIES")
print("=" * 60)

display(probability_results.round(4))

print("\nProbability represents the model's confidence in its predicted class.")
print("Values closer to 1.0000 indicate higher prediction confidence.")

print("\n✅ Prediction probabilities generated successfully.")

PREDICTION PROBABILITIES
============================================================

,Record,Actual Class,Logistic Regression Probability,Decision Tree Probability,Random Forest Probability
0,1,Phishing,1.0000,1.0,1.0
1,2,Legitimate,1.0000,1.0,1.0
2,3,Legitimate,1.0000,1.0,1.0
3,4,Legitimate,1.0000,1.0,1.0
4,5,Phishing,1.0000,1.0,1.0
5,6,Phishing,1.0000,1.0,1.0
6,7,Legitimate,1.0000,1.0,1.0
7,8,Phishing,1.0000,1.0,1.0
8,9,Legitimate,1.0000,1.0,1.0
9,10,Legitimate,0.9999,1.0,1.0

Probability represents the model's confidence in its predicted class.
Values closer to 1.0000 indicate higher prediction confidence.

✅ Prediction probabilities generated successfully.

In [8]:
# Compare model predictions with the actual class

comparison_results = pd.DataFrame({
    "Actual": y_actual.map(class_mapping).to_numpy(),
    "Logistic Regression": predictions["Logistic Regression"].astype(int),
    "Decision Tree": predictions["Decision Tree"].astype(int),
    "Random Forest": predictions["Random Forest"].astype(int)
})

# Calculate whether each model predicted correctly
for model_name in models:
    comparison_results[f"{model_name} Correct"] = (
        comparison_results["Actual"].map(
            {"Phishing": 0, "Legitimate": 1}
        ) == comparison_results[model_name]
    )

print("PREDICTION VERIFICATION")
print("=" * 60)

display(comparison_results)

print("\nCorrect Predictions:")
for model_name in models:
    correct = comparison_results[f"{model_name} Correct"].sum()
    total = len(comparison_results)

    print(f"{model_name}: {correct}/{total}")

print("\n✅ Predictions compared with actual classes successfully.")

PREDICTION VERIFICATION
============================================================

,Actual,Logistic Regression,Decision Tree,Random Forest,Logistic Regression Correct,Decision Tree Correct,Random Forest Correct
0,Phishing,0,0,0,True,True,True
1,Legitimate,1,1,1,True,True,True
2,Legitimate,1,1,1,True,True,True
3,Legitimate,1,1,1,True,True,True
4,Phishing,0,0,0,True,True,True
5,Phishing,0,0,0,True,True,True
6,Legitimate,1,1,1,True,True,True
7,Phishing,0,0,0,True,True,True
8,Legitimate,1,1,1,True,True,True
9,Legitimate,1,1,1,True,True,True

Correct Predictions:
Logistic Regression: 10/10
Decision Tree: 10/10
Random Forest: 10/10

✅ Predictions compared with actual classes successfully.

In [10]:
# Load evaluation results from Notebook 08

import os

evaluation_file = "../results/evaluation_results.csv"

print("FINAL MODEL SELECTION")
print("=" * 60)

if os.path.exists(evaluation_file):

    evaluation_df = pd.read_csv(evaluation_file)

    print("Evaluation results loaded successfully.")
    print("\nModel Comparison:")
    display(evaluation_df.round(4))

    # Select model with highest F1-score
    best_model_name = evaluation_df.loc[
        evaluation_df["F1-Score"].idxmax(),
        "Model"
    ]

    best_f1_score = evaluation_df.loc[
        evaluation_df["F1-Score"].idxmax(),
        "F1-Score"
    ]

    final_model = models[best_model_name]

    print("\n" + "=" * 60)
    print("FINAL MODEL")
    print("=" * 60)

    print("Selected Model:", best_model_name)
    print(f"F1-Score: {best_f1_score:.4f}")

    print("\nModel Type:", type(final_model).__name__)

else:

    print("Evaluation results file was not found.")
    print("\nPlease run this cell in Notebook 08 first:")
    print("evaluation_df.to_csv('../results/evaluation_results.csv', index=False)")

FINAL MODEL SELECTION
============================================================
Evaluation results file was not found.

Please run this cell in Notebook 08 first:
evaluation_df.to_csv('../results/evaluation_results.csv', index=False)

In [13]:
# Final Model Selection and Prediction

import pandas as pd
import numpy as np
import joblib
from sklearn.metrics import f1_score

print("FINAL MODEL SELECTION AND PREDICTION")
print("=" * 60)

# ---------------------------------------------------------
# 1. Generate predictions for the sample using all models
# ---------------------------------------------------------

model_predictions = {}

for model_name, model in models.items():

    if model_name in ["Logistic Regression", "Decision Tree"]:
        X_input = scaler.transform(X_sample)
    else:
        # Random Forest uses unscaled features
        X_input = X_sample

    model_predictions[model_name] = model.predict(X_input)

# ---------------------------------------------------------
# 2. Calculate F1-score on the sample
# ---------------------------------------------------------

model_f1_scores = {}

for model_name in models:

    score = f1_score(
        y_actual,
        model_predictions[model_name]
    )

    model_f1_scores[model_name] = score

# Display sample F1-scores
f1_table = pd.DataFrame(
    list(model_f1_scores.items()),
    columns=["Model", "F1-Score"]
)

print("Sample Prediction Model Comparison")
print("=" * 60)

display(f1_table.round(4))

# ---------------------------------------------------------
# 3. Select model
# ---------------------------------------------------------

best_model_name = max(
    model_f1_scores,
    key=model_f1_scores.get
)

final_model = models[best_model_name]

print("\nSelected Final Model:", best_model_name)
print(f"Sample F1-Score: {model_f1_scores[best_model_name]:.4f}")

# ---------------------------------------------------------
# 4. Generate final prediction
# ---------------------------------------------------------

if best_model_name in ["Logistic Regression", "Decision Tree"]:
    X_final_input = scaler.transform(X_sample)
else:
    X_final_input = X_sample

final_predictions = final_model.predict(X_final_input)

final_probabilities = final_model.predict_proba(X_final_input)

prediction_confidence = np.max(
    final_probabilities,
    axis=1
)

# ---------------------------------------------------------
# 5. Create final prediction table
# ---------------------------------------------------------

class_mapping = {
    0: "Phishing",
    1: "Legitimate"
}

final_results = pd.DataFrame({
    "Record": range(1, len(X_sample) + 1),
    "Actual Class": y_actual.map(class_mapping).to_numpy(),
    "Predicted Class": pd.Series(final_predictions).map(class_mapping).to_numpy(),
    "Confidence": prediction_confidence
})

print("\nFINAL PREDICTION RESULTS")
print("=" * 60)

display(final_results.round(4))

print("\n✅ Final prediction completed successfully.")

FINAL MODEL SELECTION AND PREDICTION
============================================================
Sample Prediction Model Comparison
============================================================

c:\Users\Hitesh\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
c:\Users\Hitesh\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

                 Model  F1-Score
0  Logistic Regression       1.0
1        Decision Tree       1.0
2        Random Forest       1.0

Selected Final Model: Logistic Regression
Sample F1-Score: 1.0000

FINAL PREDICTION RESULTS
============================================================

c:\Users\Hitesh\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
c:\Users\Hitesh\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

   Record Actual Class Predicted Class  Confidence
0       1     Phishing        Phishing      1.0000
1       2   Legitimate      Legitimate      1.0000
2       3   Legitimate      Legitimate      1.0000
3       4   Legitimate      Legitimate      1.0000
4       5     Phishing        Phishing      1.0000
5       6     Phishing        Phishing      1.0000
6       7   Legitimate      Legitimate      1.0000
7       8     Phishing        Phishing      1.0000
8       9   Legitimate      Legitimate      1.0000
9      10   Legitimate      Legitimate      0.9999

✅ Final prediction completed successfully.

In [14]:
# Final Model Selection and Prediction

import pandas as pd
import numpy as np
import joblib
from sklearn.metrics import f1_score

print("FINAL MODEL SELECTION AND PREDICTION")
print("=" * 60)

# ---------------------------------------------------------
# 1. Generate predictions for the sample using all models
# ---------------------------------------------------------

model_predictions = {}

for model_name, model in models.items():

    if model_name in ["Logistic Regression", "Decision Tree"]:
        X_input = scaler.transform(X_sample)
    else:
        # Random Forest uses unscaled features
        X_input = X_sample

    model_predictions[model_name] = model.predict(X_input)

# ---------------------------------------------------------
# 2. Calculate F1-score on the sample
# ---------------------------------------------------------

model_f1_scores = {}

for model_name in models:

    score = f1_score(
        y_actual,
        model_predictions[model_name]
    )

    model_f1_scores[model_name] = score

# Display sample F1-scores
f1_table = pd.DataFrame(
    list(model_f1_scores.items()),
    columns=["Model", "F1-Score"]
)

print("Sample Prediction Model Comparison")
print("=" * 60)

display(f1_table.round(4))

# ---------------------------------------------------------
# 3. Select model
# ---------------------------------------------------------

best_model_name = max(
    model_f1_scores,
    key=model_f1_scores.get
)

final_model = models[best_model_name]

print("\nSelected Final Model:", best_model_name)
print(f"Sample F1-Score: {model_f1_scores[best_model_name]:.4f}")

# ---------------------------------------------------------
# 4. Generate final prediction
# ---------------------------------------------------------

if best_model_name in ["Logistic Regression", "Decision Tree"]:
    X_final_input = scaler.transform(X_sample)
else:
    X_final_input = X_sample

final_predictions = final_model.predict(X_final_input)

final_probabilities = final_model.predict_proba(X_final_input)

prediction_confidence = np.max(
    final_probabilities,
    axis=1
)

# ---------------------------------------------------------
# 5. Create final prediction table
# ---------------------------------------------------------

class_mapping = {
    0: "Phishing",
    1: "Legitimate"
}

final_results = pd.DataFrame({
    "Record": range(1, len(X_sample) + 1),
    "Actual Class": y_actual.map(class_mapping).to_numpy(),
    "Predicted Class": pd.Series(final_predictions).map(class_mapping).to_numpy(),
    "Confidence": prediction_confidence
})

print("\nFINAL PREDICTION RESULTS")
print("=" * 60)

display(final_results.round(4))

print("\n✅ Final prediction completed successfully.")

FINAL MODEL SELECTION AND PREDICTION
============================================================
Sample Prediction Model Comparison
============================================================

c:\Users\Hitesh\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
c:\Users\Hitesh\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

                 Model  F1-Score
0  Logistic Regression       1.0
1        Decision Tree       1.0
2        Random Forest       1.0

Selected Final Model: Logistic Regression
Sample F1-Score: 1.0000

FINAL PREDICTION RESULTS
============================================================

c:\Users\Hitesh\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
c:\Users\Hitesh\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

   Record Actual Class Predicted Class  Confidence
0       1     Phishing        Phishing      1.0000
1       2   Legitimate      Legitimate      1.0000
2       3   Legitimate      Legitimate      1.0000
3       4   Legitimate      Legitimate      1.0000
4       5     Phishing        Phishing      1.0000
5       6     Phishing        Phishing      1.0000
6       7   Legitimate      Legitimate      1.0000
7       8     Phishing        Phishing      1.0000
8       9   Legitimate      Legitimate      1.0000
9      10   Legitimate      Legitimate      0.9999

✅ Final prediction completed successfully.

In [15]:
# Final prediction summary

print("FINAL PREDICTION SUMMARY")
print("=" * 60)

# Count predictions by class
prediction_counts = final_results["Predicted Class"].value_counts()

print("\nPrediction Distribution:")
display(prediction_counts.to_frame("Number of Records"))

# Calculate number of correct predictions
correct_predictions = (
    final_results["Actual Class"] ==
    final_results["Predicted Class"]
).sum()

total_predictions = len(final_results)

accuracy = correct_predictions / total_predictions

print("\nPrediction Verification")
print("-" * 60)
print("Total sample records:", total_predictions)
print("Correct predictions:", correct_predictions)
print("Incorrect predictions:", total_predictions - correct_predictions)
print(f"Sample accuracy: {accuracy:.4f}")

print("\nFinal Model:", best_model_name)

print("\nClass Interpretation:")
print("0 → Phishing")
print("1 → Legitimate")

print("\n" + "=" * 60)
print("✅ NOTEBOOK 09 — FINAL PREDICTION COMPLETED")
print("=" * 60)

FINAL PREDICTION SUMMARY
============================================================

Prediction Distribution:

                 Number of Records
Predicted Class
Legitimate                       6
Phishing                         4

Prediction Verification
------------------------------------------------------------
Total sample records: 10
Correct predictions: 10
Incorrect predictions: 0
Sample accuracy: 1.0000

Final Model: Logistic Regression

Class Interpretation:
0 → Phishing
1 → Legitimate

============================================================
✅ NOTEBOOK 09 — FINAL PREDICTION COMPLETED
============================================================